version: '3'

services:
  web:
    build:
      dockerfile: docker/web/Dockerfile
      context: .
    expose:
      - "443"
    volumes:
      - ./:/var/www/project
      - ./docker/web/site.conf:/etc/nginx/conf.d/default.conf
    environment:
      VIRTUAL_HOST: ${HOST},www.${HOST}
        #      HTTPS_METHOD: redirect
      VIRTUAL_PORT: 443
      LETSENCRYPT_HOST: ${HOST},www.${HOST}
    depends_on:
      - php
    networks:
      - internal
      - nginx-proxy
  php:
    build:
      dockerfile: docker/php/Dockerfile
      context: .
    volumes:
      - ./:/var/www/project
    networks:
      - internal

networks:
  internal:
  nginx-proxy:
    external:
      name: nginx-proxy
